[package]
name = "flurry"
version = "0.1.0"
authors = ["the snowflake authors <whiskerdev@protonmail.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
tag = { path = "../../lib/tag" }
parser = { path = "../../lib/parser" }
